spec:
  template:
    spec:
      containers:
        -
          resources:
            requests:
              cpu: "0.2"
            limits:
              cpu: "1.0"
          env:
          - name: ACTIVEMQ_SERVICE_NAME
            value: broker-amq-tcp
